version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: footychat-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: footychat
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: footychat-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build: ./server
    container_name: footychat-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/footychat?authSource=admin
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: footychat-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:
  redis_data: